export const ADD_INGREDIENTS ='ADD_INGREDIENTS';

export const SHOW_ORDERS_START ='SHOW_ORDERS_START';


export const SHOW_ORDERS_SUCCESS ='SHOW_ORDERS_SUCCESS';


export const SHOW_ORDERS_FAILED ='SHOW_ORDERS_FAILED';

